title: Alexander Palomares
logo: 20241127_134152.jpg
description: Explore my portfolio showcasing recent cybersecurity projects and labs that I’ve worked on. These experiences not only deepened my skills but also provided valuable insights into real-world security challenges.
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal
