title: Alexander Palomares
logo: 20241127_134152.jpg
description: Check out my portfolio of recent cybersecurity projects and labs that sharpened my skills and provided me with valuable new insights.
#show_downloads: true
#google_analytics: 
theme: jekyll-theme-minimal
